on:
  pull_request: {}
  push:
    branches:
      - "*"
    paths:
      - "*"
      - .github/**
      - fixtures/**
      - packages/ts/**

jobs:
  unit:
    runs-on: ubuntu-latest
    container: node:20.11-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm --workspaces run build
      - run: npm --workspaces test

  audit:
    runs-on: ubuntu-latest
    container: node:20.11-alpine3.19
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm --workspaces audit --audit-level high
